//! Raw FFI bindings to libcwist, the CWIST C web framework.
//!
//! Generated by bindgen at build time from the installed CWIST headers (see
//! `build.rs` and `wrapper.h`); libcwist and its bundled dependencies are
//! linked statically through `cwist.pc`. Everything here is `unsafe` and
//! mirrors the C API one to one. A safe wrapper is planned as a separate
//! `cwist` crate (ROADMAP.md, v3.8 Phase 2).
//!
//! # ABI notes
//!
//! * The layouts of `cwist_http_request`, `cwist_http_response`,
//!   `cwist_http_header_node`, `cwist_sstring` and `cwist_error_t` are pinned
//!   on the C side by `tests/abi_layout.h`; bindgen additionally checks the
//!   generated Rust layouts against the C compiler at build time.
//! * `cwist_app`, `cwist_query_map`, `cwist_db`, `cJSON` and `sqlite3` are
//!   opaque: use them through pointers only.
//! * C enums are plain integer constants (for example `CWIST_HTTP_OK`), so a
//!   value the C side adds later is still a valid Rust value.
//! * `static inline` C helpers have exported forms with an `_extern` suffix,
//!   such as [`cwist_error_is_ok_extern`].
//!
//! # Ownership
//!
//! Routes registered with the `cwist_app_*_ex` functions take ownership of
//! `user_ctx` when a destructor is passed: the app calls it exactly once,
//! including when registration fails. Handlers run on CWIST worker threads
//! and must not unwind across the FFI boundary. Memory allocated by Rust stays
//! outside `cwist_alloc`, so CWIST's full GC and `CWIST_INTERCEPT_MALLOC` do
//! not apply to it; buffers CWIST hands out (for example the response of
//! [`cwist_app_dispatch_memory`]) are released with [`cwist_free`].

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
